/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'task';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String BANNER1 = 'assets/images/banner1.jpg';
  static const String BANNER2 = 'assets/images/banner2.jpg';
  static const String BANNER3 = 'assets/images/banner3.jpg';
  static const String BANNER4 = 'assets/images/banner4.jpg';
  static const String BANNER5 = 'assets/images/banner5.jpg';
}
